# Generated by Django 3.2.4 on 2021-07-06 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRUEBAAPP', '0002_contacto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=8)),
                ('edad', models.IntegerField()),
            ],
        ),
    ]
