# Generated by Django 3.2.4 on 2021-07-06 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PRUEBAAPP', '0003_persona'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Persona',
        ),
    ]
