# Generated by Django 3.2.5 on 2021-07-05 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PRUEBAAPP', '0003_contacto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito',
            name='total_carrito',
        ),
    ]
