# Generated by Django 3.2.5 on 2021-07-05 23:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PRUEBAAPP', '0004_remove_carrito_total_carrito'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario_carrito', to=settings.AUTH_USER_MODEL),
        ),
    ]
